recipe_project/recipe_catalog/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'recipe_catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('recipe/', views.recipe, name='recipe'),
    path('recipe/<int:pk>/', views.recipe_detail, name='recipe_detail'),
    path('recipe/<int:pk>/edit/', views.recipe_edit, name='recipe_edit'),
    path('recipe/<int:pk>/delete/', views.recipe_delete, name='recipe_delete'),
    path('about/', views.about, name='about'),
    path('form_user_test/', views.form_user_test, name='create_user_test'),
    path('ingredients/', views.ingredients, name='ingredients'),
    path('ingredient/', views.ingredient, name='ingredient'),
    path(
        'ingredient/<int:pk>/edit/',
        views.ingredient_edit,
        name='ingredient_edit'
    ),
    path(
        'ingredient/<int:pk>/delete/',
        views.ingredient_delete,
        name='ingredient_delete'
    ),
    path('auth/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_project/recipe_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe_catalog.urls')),
]

recipe_project/recipe_catalog/models.py
from django.db import models
from datetime import timedelta
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    weight = models.PositiveIntegerField()
    weight_ready = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=300, db_index=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='recipe_images/', blank=True, null=True)
    cooking_time = models.DurationField(default=timedelta(minutes=5))
    ingredients = models.ManyToManyField(Ingredient, through='RecipeIngredient')
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return self.title

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.ingredient} - {self.recipe}'

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['recipe', 'ingredient'],
                name='unique_recipe_ingredient'
            ),
        ]
        indexes = [
            models.Index(fields=['recipe', 'ingredient'])
        ]

recipe_project/recipe_catalog/forms.py
from django import forms

from recipe_catalog.models import Ingredient, Recipe

class UserForm(forms.Form):
    first_name = forms.CharField(label='First name', max_length=100)
    last_name = forms.CharField(label='Last name', max_length=100, required=False)
    email = forms.EmailField(label='Email', required=False)

class IngredientForm(forms.ModelForm):
    class Meta:
        fields = ('name', 'weight', 'weight_ready', 'price',)
        labels = {
            'name': 'Name',
            'weight': 'Weight',
            'weight_ready': 'Weight ready',
            'price': 'Price'
        }
        help_texts = {
            'name': 'Enter the name of the ingredient',
            'weight': 'Enter the weight of the ingredient in grams',
            'weight_ready': 'Enter the weight of the ingredient in grams after cooking',
            'price': 'Enter the price of the ingredient in rubles'
        }
        model = Ingredient

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        exclude = ('author',)
        fields = ('title', 'description', 'cooking_time', 'image', 'ingredients')
        labels = {
            'title': 'Title',
            'description': 'Description',
            'cooking_time': 'Cooking time',
            'image': 'Image',
            'ingredients': 'Ingredients'
        }
        help_texts = {
            'title': 'Enter the title of the recipe',
            'description': 'Enter the description of the recipe',
            'cooking_time': 'Enter the cooking time of the recipe in minutes',
            'image': 'Upload an image for the recipe',
            'ingredients': 'Select the ingredients for the recipe'
        }
        widgets = {
            'image': forms.FileInput(attrs={'accept': 'image/*'}),
            'description': forms.Textarea(attrs={'rows': 4}),
            'ingredients': forms.SelectMultiple(attrs={'class': 'select2'}),
        }

recipe_project/recipe_catalog/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from .forms import IngredientForm, RecipeForm, UserForm
from .models import Ingredient, Recipe


# Главная страница, Вывод списка рецептов
def index(request):
    recipes_list = Recipe.objects.order_by('title')
    paginator = Paginator(recipes_list, 10)
    page_number = request.GET.get('page')
    recipes = paginator.get_page(page_number)
    return render(request, 'recipe_catalog/index.html', {'recipes': recipes})


def about(request):
    return render(request, 'recipe_catalog/about.html')


def recipe_detail(request, pk):
    try:
        recipe = Recipe.objects.get(pk=pk)
    except Recipe.DoesNotExist:
        return handle_error_404(request)
    context = {
        'recipe_id': recipe.id,
        'title': recipe.title,
        'cooking_time': recipe.cooking_time,
        'image': recipe.image,
        'description': recipe.description,
        'ingredients': recipe.ingredients.order_by('name'),
    }
    return render(request, 'recipe_catalog/recipe.html', context)


def handle_error_404(request):
    return render(request, 'recipe_catalog/404.html', status=404)


def form_user_test(request):
    """Test form for user"""
    if request.GET:
        form = UserForm(request.GET)
        if form.is_valid():
            pass
    else:
        form = UserForm()
    context = {'form': form}
    return render(request, 'recipe_catalog/form_user_test.html', context)


@login_required
def ingredient(request):
    form = IngredientForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {'form': form}
    return render(request, 'recipe_catalog/ingredient_form.html', context)


def ingredient_edit(request, pk):
    if not request.user.is_authenticated:
        return redirect('recipe_catalog:login')
    instance = get_object_or_404(Ingredient, pk=pk)
    if request.method == 'POST':
        form = IngredientForm(request.POST or None, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('recipe_catalog:ingredients')
    else:
        form = IngredientForm(instance=instance)
    context = {'form': form}
    return render(request, 'recipe_catalog/ingredient_form.html', context)


def ingredients(request):
    ingredients = Ingredient.objects.all()
    context = {'ingredients': ingredients}
    return render(request, 'recipe_catalog/ingredients.html', context)


def ingredient_delete(request, pk):
    instance = get_object_or_404(Ingredient, pk=pk)
    form = IngredientForm(instance=instance)
    context = {'form': form}
    if request.method == 'POST':
        instance.delete()
        return redirect('recipe_catalog:ingredients')
    return render(request, 'recipe_catalog/ingredient_form.html', context)


@login_required
def recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            form.save_m2m()
            return redirect('recipe_catalog:recipe_detail', pk=instance.pk)
    else:
        form = RecipeForm()
    context = {'form': form}
    return render(request, 'recipe_catalog/recipe_form.html', context)


def recipe_edit(request, pk):
    if not request.user.is_authenticated:
        return redirect('recipe_catalog:login')
    instance = get_object_or_404(Recipe, pk=pk)
    if instance.author != request.user:
        # raise PermissionDenied
        return HttpResponse('You can not edit this recipe')
    form = RecipeForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect('recipe_catalog:recipe_detail', pk=instance.pk)
    context = {'form': form}
    return render(request, 'recipe_catalog/recipe_form.html', context)


@login_required
def recipe_delete(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    form = RecipeForm(instance=recipe)
    context = {'form': form}
    if request.method == 'POST':
        if recipe.author != request.user:
            raise PermissionDenied
        else:
            recipe.delete()
            return redirect('recipe_catalog:index')
    return render(request, 'recipe_catalog/recipe_form.html', context)

recipe_project/templates/recipe_catalog/about.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="description" content="О нашем сервисе рецептов">
    <title>О нашем сервисе</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <header>
            <nav class="w3-bar w3-black">
                <a href="/" class="w3-bar-item w3-button">Главная страница</a>
                <a href="{% url 'recipe_catalog:about' %}" class="w3-bar-item w3-button">О сайте</a>
            </nav>
        </header>
        <main class="w3-container main-content">
            <h1>О нашем сервисе</h1>
            <p>Наш сервис предоставляет удобный каталог рецептов, обновляемых в реальном времени. Вы можете изучить разные рецепты, узнать ингредиенты и их количество, и даже добавить свои идеи!</p>
        </main>
        <footer class="footer w3-black w3-center w3-padding-16">
            <p>Подвал © 2024</p>
        </footer>
    </div>
</body>
</html>

recipe_project/templates/recipe_catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="description" content="Главная страница с рецептами">
    <title>Рецептики мои любимые!</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <div class="container">
        <header>
            <nav class="w3-bar w3-black">
                <a href="/" class="w3-bar-item w3-button">Главная страница</a>
                <a href="{% url 'recipe_catalog:about' %}" class="w3-bar-item w3-button">О сайте</a>
            </nav>
        </header>
        <main class="w3-container main-content">
            {% block content %}
            {% endblock %}
        </main>
        <footer class="footer">
            <p>Подвал © 2024</p>
        </footer>
    </div>
</body>

</html>

recipe_project/templates/recipe_catalog/form_user_test.html
{% extends 'recipe_catalog/base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" value="Submit">Отправить</button>
    </form>
    {% if request.GET %}
    <h2>Hello, {{ request.GET.first_name }}</h2>
    {% endif %}
</div>
{% endblock %}

recipe_project/templates/recipe_catalog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="description" content="Главная страница с рецептами">
    <title>Рецептики мои любимые!</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <div class="container">
        <header>
            <nav class="w3-bar w3-black">
                <a href="/" class="w3-bar-item w3-button">Главная страница</a>
                <a href="{% url 'recipe_catalog:about' %}" class="w3-bar-item w3-button">О сайте</a>
            </nav>
        </header>
        <main class="w3-container main-content">
            <h1>Главная страница</h1>
            <div>Добро пожаловать! Ниже приведены наши рецепты:</div>
            <div>
                {% for recipe in recipes %}
                <p>
                    <a href="{% url 'recipe_catalog:recipe_detail' recipe.id %}" class="w3-bar-item w3-button">
                        {{ recipe.title }}
                    </a>
                </p>
                {% empty %}
                <p>Рецептов пока нет.</p>
                {% endfor %}
            </div>
        </main>
        <footer class="footer">
            <p>Подвал © 2024</p>
        </footer>
    </div>
</body>

</html>

recipe_project/templates/recipe_catalog/ingredient_form.html
{% extends 'recipe_catalog/base.html' %}

{% block content %}
<h2>Ingredient</h2>
{% with data=form.instance %}
<form method="post">
    {% csrf_token %}
    {% if not "/delete" in request.path %}
    {{ form.as_p }}
    {% else %}
    <p>{{ data.name }}</p>
    <p>Вес {{ data.weight }} g</p>
    <p>Вес после готовки {{ data.weight_ready }} g</p>
    <p>{{ data.price }} руб</p>
    {% endif %}
    <input type="submit" value="Submit">
</form>
{% if form.is_valid %}
ID new ingredient: {{ data.id }}
{% endif %}
{% endwith %}
{% endblock content %}

recipe_project/templates/recipe_catalog/ingredients.html
{% extends 'recipe_catalog/base.html' %}

{% block content %}
<h2>Ingredients</h2>
<p>ID Name Weight Ready Price</p>
{% for ingredient in ingredients %}
<p>{{ ingredient.id }} {{ ingredient.name }} {{ ingredient.weight }} {{ ingredient.weight_ready }} {{ ingredient.price }}
</p><br>
{% endfor %}
{% endblock content %}

recipe_project/templates/recipe_catalog/login.html
{% extends 'recipe_catalog/base.html' %}

{% block content %}
<form action="{% url 'recipe_catalog:login' %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock %}

recipe_project/templates/recipe_catalog/recipe.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Страница рецепта {{ title }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }} - Наши Рецепты</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <header>
            <nav class="w3-bar w3-black">
                <a href="/" class="w3-bar-item w3-button">Главная страница</a>
                <a href="{% url 'recipe_catalog:about' %}" class="w3-bar-item w3-button">О сайте</a>
            </nav>
        </header>
        <main class="w3-container main-content">
            <h1>{{ title }}</h1>
            <p>Время готовки: {{ cooking_time }}</p>
            <hr>
            <p>{{ description }}</p>
            <hr>
            {% if image %}
            <img src="{{ image.url }}" alt="Изображение {{ title }}" class="w3-image" width="30%">
            {% endif %}
            <h2>Ингредиенты:</h2>
            <table class="w3-table-all w3-hoverable" border="1">
                <thead>
                    <tr>
                        <th>Ингредиент</th>
                        <th>Вес (сырой), г</th>
                        <th>Вес (готовый), г</th>
                        <th>Стоимость, р</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ingredient in ingredients %}
                    <tr>
                        <td>{{ ingredient.name }}</td>
                        <td>{{ ingredient.weight }}</td>
                        <td>{{ ingredient.weight_ready }}</td>
                        <td>{{ ingredient.price }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
        <footer class="footer w3-black w3-center w3-padding-16">
            <p>&copy; Рецепты на любой вкус</p>
        </footer>
    </div>
</body>
</html>

recipe_project/templates/recipe_catalog/recipe_form.html
{% extends 'recipe_catalog/base.html' %}

{% block content %}
<h2>Recipe</h2>
{% with data=form.instance %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if not "/delete" in request.path %}
    {{ form.as_p }}
    {% else %}
    <p>{{ data.title }}</p>
    <p>{{ data.description }}</p>
    <p>Время готовки {{ data.cooking_time }} мин</p>
    <p>{{ data.author }}</p>
    {% endif %}
    <input type="submit" value="Submit">
</form>
{% if form.is_valid %}
ID new ingredient: {{ data.id }}
{% endif %}
{% endwith %}
{% endblock content %}